name: falconmetrics_flutter
description: "Flutter plugin for FalconMetrics, a comprehensive mobile app attribution solution."
version: 1.2.0
homepage: https://falconmetrics.io

environment:
  sdk: ^3.7.0
  flutter: '>=3.6.0'

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: io.falconmetrics.falconmetrics_flutter
        pluginClass: FalconmetricsFlutterPlugin
      ios:
        pluginClass: FalconmetricsFlutterPlugin
